# Generated by Django 5.2.6 on 2025-11-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vacationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
