# Generated by Django 5.2.6 on 2025-11-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vacationmodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
