# Generated by Django 5.2.6 on 2025-11-28 18:54

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_vacationmodel_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_days', models.IntegerField(default=1)),
                ('ondate', models.DateField(default=api.models.tomorrow)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vacationmodel')),
            ],
        ),
    ]
